apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      name: amf
      labels:
        app: amf
    spec:
      serviceAccountName: developer-sa
      containers:
        - name: amf
          image: luthfizulkifli/5gamf:v10
          command: ["/bin/sh"]
          args: ["-c","depmod && modprobe sctp && setsid ./open5gs/install/bin/open5gs-amfd && sleep infinity"]
          securityContext:
            runAsUser: 0
            privileged: true
