apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      serviceAccountName: developer-sa
      containers:
        - name: mongodb
          image: luthfizulkifli/5gmongodb:v1
          command: ["/bin/sh"]
          args: ["-c","setsid ./open5gs/startmongodb.sh && sleep infinity"]
          securityContext:
            runAsUser: 0
            privileged: true
