apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      serviceAccountName: developer-sa
      containers:
        - name: mongodb
          image: luthfizulkifli/5gmongodb:v1
          command: ["/bin/sh"]
          args: ["-c","setsid ./open5gs/startmongodb.sh && sleep infinity"]
          securityContext:
            runAsUser: 0
            privileged: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      name: amf
      labels:
        app: amf
    spec:
      serviceAccountName: developer-sa
      containers:
        - name: amf
          image: luthfizulkifli/5gamf:v10
          command: ["/bin/sh"]
          args: ["-c","depmod && modprobe sctp && setsid ./open5gs/install/bin/open5gs-amfd && sleep infinity"]
          securityContext:
            runAsUser: 0
            privileged: true


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ausf
  template:
    metadata:
      name: ausf
      labels:
        app: ausf
    spec:
      serviceAccountName: developer-sa
      containers:
        - name: ausf
          image: luthfizulkifli/5gausf:v1
          command: ["/bin/sh"]
          args: ["-c","setsid ./open5gs/install/bin/open5gs-ausfd && sleep infinity"]
          #args: ["-c","sleep infinity"]
          securityContext:
            runAsUser: 0
            privileged: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrf
  template:
    metadata:
      name: nrf
      labels:
        app: nrf
    spec:
      serviceAccountName: developer-sa
      containers:
      - name: nrf
        image: luthfizulkifli/5gnrf:v1
        command: ["/bin/sh"]
        args: ["-c","setsid ./open5gs/install/bin/open5gs-nrfd && sleep infinity"]
        #command: ["/bin/sh"]
        #args: ["-c","./open5gs/install/bin/open5gs-nrfd && sleep infinity"]
        securityContext:
        #privileged: true
            #fsGroup: 0
            #Group: 0
          runAsUser: 0
          privileged: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      name: smf
      labels:
        app: smf
    spec:
      serviceAccountName: developer-sa
      containers:
        - name: smf
          image: luthfizulkifli/5gsmf:v2
          command: ["/bin/sh"]
          args: ["-c","setsid ./open5gs/install/bin/open5gs-smfd && sleep infinity"]
          securityContext:
            runAsUser: 0
            privileged: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udm
  template:
    metadata:
      name: udm
      labels:
        app: udm
    spec:
      serviceAccountName: developer-sa
      containers:
        - name: udm
          image: luthfizulkifli/5gudm:v1
          command: ["/bin/sh"]
          args: ["-c","setsid ./open5gs/install/bin/open5gs-udmd && sleep infinity"]
          securityContext:
            runAsUser: 0
            privileged: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udr
  template:
    metadata:
      name: udr
      labels:
        app: udr
    spec:
      serviceAccountName: developer-sa
      containers:
      - name: udr
        image: luthfizulkifli/5gudr:v1
        command: ["/bin/sh"]
        args: ["-c","setsid ./open5gs/install/bin/open5gs-udrd && sleep infinity"]
        securityContext:
          runAsUser: 0
          privileged: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uegnb
spec:
  selector:
    matchLabels:
      app: uegnb2
  template:
    metadata:
      name: uegnb2
      labels:
        app: uegnb2
    spec:
      serviceAccountName: developer-sa
      containers:
        - name: uegnb
          image: openverso/ueransim:3.2.6
          command: ["/bin/sh"]
          args: ["-c","sleep infinity"]
          securityContext:
            runAsUser: 0
            privileged: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      name: upf
      labels:
        app: upf
    spec:
      serviceAccountName: developer-sa
      containers:
        - name: upf
          image: luthfizulkifli/5gupf:v2
          command: ["/bin/sh"]
          args: ["-c","ip tuntap add name ogstun mode tun && ip addr add 10.45.0.1/16 dev ogstun && ip link set ogstun up && setsid ./open5gs/install/bin/open5gs-upfd && sleep infinity"]
          volumeMounts:
          - mountPath: /dev/net/tun
            name: dev-tun
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            runAsUser: 0
            privileged: true
      volumes:
      - hostPath:
          path: /dev/net/tun
          type: CharDevice
        name: dev-tun
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      name: webui
      labels:
        app: webui
    spec:
      serviceAccountName: developer-sa
      containers:
        - name: webui
          image: luthfizulkifli/webui:v2
          command: ["/bin/sh"]
          args: ["-c","cd /open5gs/webui/ && setsid npm run start && sleep infinity"]
          securityContext:
            runAsUser: 0
            privileged: true
