apiVersion: v1
kind: Service
metadata:
  name: amf
spec:
  clusterIP: 10.217.4.233
  selector:
    app: amf
  ports:
    - name: sbi-port
      port: 7777
      targetPort: 7777
      protocol: TCP
    - name: sctpserver
      port: 38412
      targetPort: 38412
      protocol: SCTP
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ausf
spec:
  clusterIP: 10.217.4.236
  selector:
    app: ausf
  ports:
    - name: sbi-port      
      protocol: TCP
      port: 7777
      targetPort: 7777
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  clusterIP: 10.217.4.239
  selector:
    app: mongodb
  ports:
    - name: mongodb-port
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: nrf
spec:
  clusterIP: 10.217.4.232
  selector:
    app: nrf
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: smf
spec:
  clusterIP: 10.217.4.234
  selector:
    app: smf
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: udm
spec:
  clusterIP: 10.217.4.237
  selector:
    app: udm
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: udr
spec:
  clusterIP: 10.217.4.238
  selector:
    app: udr
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: upf
spec:
  clusterIP: 10.217.4.235
  selector:
    app: upf
  ports:
    - name: pfcp-port
      protocol: UDP
      port: 8805
      targetPort: 8805
    - name: gtpu-port
      protocol: UDP
      port: 2152
      targetPort: 2152
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  clusterIP: 10.217.4.241
  selector:
    app: webui
  ports:
    - name: webui-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
