apiVersion: v1
kind: Service
metadata:
  name: amf
spec:
  clusterIP: 10.217.4.233
  selector:
    app: amf
  ports:
    - name: sbi-port
      port: 7777
      targetPort: 7777
      protocol: TCP
    - name: sctpserver
      port: 38412
      targetPort: 38412
      protocol: SCTP
  type: NodePort
