apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  clusterIP: 10.217.4.239
  selector:
    app: mongodb
  ports:
    - name: mongodb-port
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort
